version: '3.7'

services:
  proxy:
    image: vtb_proxy
    build:
      context: ./proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "3000:8080"
  frontend:
    image: vtb_frontend
    build:
      context: ./frontend
      args:
        FRONTEND_PRODUCTION_URL: ${FRONTEND_API_URL}
    ports:
      - "80:80"
  backend:
    image: vtb_backend
    build:
      context: ./backend
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "7777:7777"
    depends_on:
      - db
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/data/
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
# volumes:
#   postgres_data: